// AUTO-GENERATED by _gen_seed.py — do not edit by hand.
// Demo operational seed data (3 facilities) for the client-side self-seeder.
// Dates are ISO strings; the seeder converts them to Date and stamps the actor oid.

export interface SeedWorkOrder {
  workOrderNumber: string; equipmentId: string; instrumentId?: string; opcuaNodeId?: string
  title: string; description: string; priority: string; status: string
  assigned: boolean; createdAt: string; dueAt?: string
}
export const seedWorkOrders: SeedWorkOrder[] = [
  { workOrderNumber: "WO-2841", equipmentId: "EQUIP_RTI_T001", instrumentId: "INST_T001_VIBRATION_A", opcuaNodeId: "ns=2;s=T001.vibration_a", title: "Inspect guide bearing vibration", description: "Inspect bearing, alignment, and lubrication after elevated vibration trend.", priority: "Critical", status: "In progress", assigned: true, createdAt: "2026-07-28T08:00:00", dueAt: "2026-08-01T16:00:00" },
  { workOrderNumber: "WO-2836", equipmentId: "EQUIP_RTI_T002", instrumentId: "INST_T002_INLET_PRESSURE", opcuaNodeId: "ns=2;s=T002.inlet_pressure", title: "Review inlet pressure variance", description: "Validate transducer and compare against local gauge.", priority: "High", status: "Scheduled", assigned: true, createdAt: "2026-07-27T10:00:00", dueAt: "2026-08-03T12:00:00" },
  { workOrderNumber: "WO-2829", equipmentId: "EQUIP_RTI_T003", instrumentId: "INST_T003_TURBINE_TEMP", opcuaNodeId: "ns=2;s=T003.turbine_temp", title: "Inspect turbine cooling circuit", description: "Check strainers, flow, and temperature sensor calibration.", priority: "Medium", status: "Ready", assigned: false, createdAt: "2026-07-26T09:30:00", dueAt: "2026-08-05T12:00:00" },
  { workOrderNumber: "WO-2848", equipmentId: "EQUIP_RTI_T006", instrumentId: "INST_T006_VIBRATION_D", opcuaNodeId: "ns=2;s=T006.vibration_d", title: "Fjord unit driven-end vibration check", description: "Trend review and balancing assessment on driven-end bearing.", priority: "High", status: "Approved", assigned: true, createdAt: "2026-07-29T07:00:00", dueAt: "2026-08-04T16:00:00" },
  { workOrderNumber: "WO-2851", equipmentId: "EQUIP_RTI_T008", instrumentId: "INST_T008_POWER_OUTPUT", opcuaNodeId: "ns=2;s=T008.power_output", title: "Investigate power output dip", description: "Correlate output with head and guide-vane position.", priority: "Medium", status: "Planned", assigned: false, createdAt: "2026-07-29T13:20:00", dueAt: "2026-08-06T12:00:00" },
  { workOrderNumber: "WO-2853", equipmentId: "EQUIP_RTI_T010", instrumentId: "INST_T010_TURBINE_SPEED", opcuaNodeId: "ns=2;s=T010.turbine_speed", title: "Overspeed trip test", description: "Scheduled governor overspeed protection test.", priority: "Low", status: "Scheduled", assigned: true, createdAt: "2026-07-30T09:00:00", dueAt: "2026-08-08T12:00:00" },
  { workOrderNumber: "WO-2857", equipmentId: "EQUIP_RTI_T011", instrumentId: "INST_T011_TURBINE_TEMP", opcuaNodeId: "ns=2;s=T011.turbine_temp", title: "Highland unit cooling inspection", description: "Inspect heat exchanger fouling after temperature rise.", priority: "High", status: "In progress", assigned: true, createdAt: "2026-07-30T11:00:00", dueAt: "2026-08-02T18:00:00" },
  { workOrderNumber: "WO-2860", equipmentId: "EQUIP_RTI_T013", instrumentId: "INST_T013_VIBRATION_A", opcuaNodeId: "ns=2;s=T013.vibration_a", title: "Highland unit bearing endoscopy", description: "Borescope guide bearing following vibration advisory.", priority: "Critical", status: "Ready", assigned: false, createdAt: "2026-07-30T14:10:00", dueAt: "2026-08-03T12:00:00" },
  { workOrderNumber: "WO-2862", equipmentId: "EQUIP_RTI_T015", instrumentId: "INST_T015_INLET_PRESSURE", opcuaNodeId: "ns=2;s=T015.inlet_pressure", title: "Inlet strainer differential check", description: "Verify strainer differential pressure and clean if required.", priority: "Medium", status: "Approved", assigned: true, createdAt: "2026-07-31T08:30:00", dueAt: "2026-08-09T12:00:00" },
  { workOrderNumber: "WO-2820", equipmentId: "EQUIP_RTI_T004", instrumentId: "INST_T004_TURBINE_TEMP", opcuaNodeId: "ns=2;s=T004.turbine_temp", title: "Annual thermographic survey", description: "Completed annual thermographic survey; no anomalies.", priority: "Low", status: "Completed", assigned: true, createdAt: "2026-07-15T08:00:00", dueAt: "2026-07-20T12:00:00" },
  { workOrderNumber: "WO-2812", equipmentId: "EQUIP_RTI_T007", instrumentId: "INST_T007_VIBRATION_A", opcuaNodeId: "ns=2;s=T007.vibration_a", title: "Bearing lubrication refresh", description: "Completed lubrication service on guide bearing.", priority: "Medium", status: "Completed", assigned: true, createdAt: "2026-07-10T08:00:00", dueAt: "2026-07-14T12:00:00" },
  { workOrderNumber: "WO-2867", equipmentId: "EQUIP_RTI_T012", instrumentId: "INST_T012_POWER_OUTPUT", opcuaNodeId: "ns=2;s=T012.power_output", title: "Efficiency test after overhaul", description: "Post-overhaul efficiency verification test.", priority: "High", status: "Draft", assigned: false, createdAt: "2026-07-31T15:00:00", dueAt: "2026-08-12T12:00:00" },
]

export interface SeedNotification {
  equipmentId: string; opcuaNodeId?: string; summary: string; severity: string; status: string; reportedAt: string
}
export const seedNotifications: SeedNotification[] = [
  { equipmentId: "EQUIP_RTI_T001", opcuaNodeId: "ns=2;s=T001.vibration_a", summary: "Guide bearing vibration exceeded advisory threshold", severity: "Warning", status: "Open", reportedAt: "2026-07-30T07:42:00" },
  { equipmentId: "EQUIP_RTI_T002", opcuaNodeId: "ns=2;s=T002.inlet_pressure", summary: "Inlet pressure variance requires review", severity: "Advisory", status: "Open", reportedAt: "2026-07-30T06:15:00" },
  { equipmentId: "EQUIP_RTI_T006", opcuaNodeId: "ns=2;s=T006.vibration_d", summary: "Driven-end vibration trending upward", severity: "Warning", status: "Open", reportedAt: "2026-07-29T18:05:00" },
  { equipmentId: "EQUIP_RTI_T008", opcuaNodeId: "ns=2;s=T008.power_output", summary: "Power output below expected for head", severity: "Advisory", status: "Acknowledged", reportedAt: "2026-07-29T12:40:00" },
  { equipmentId: "EQUIP_RTI_T011", opcuaNodeId: "ns=2;s=T011.turbine_temp", summary: "Bearing temperature above normal band", severity: "Warning", status: "Open", reportedAt: "2026-07-30T10:20:00" },
  { equipmentId: "EQUIP_RTI_T013", opcuaNodeId: "ns=2;s=T013.vibration_a", summary: "Vibration advisory on guide bearing", severity: "Critical", status: "Open", reportedAt: "2026-07-30T13:55:00" },
]

export interface SeedInspection {
  equipmentId: string; opcuaNodeId?: string; inspectionType: string; result: string
  findings?: string; inspectedAt: string; nextDueAt?: string
}
export const seedInspections: SeedInspection[] = [
  { equipmentId: "EQUIP_RTI_T001", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-20T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T001", opcuaNodeId: "ns=2;s=T001.turbine_temp", inspectionType: "THERMOGRAPHIC", result: "PASS", findings: "No hot spots detected on bearings or windings.", inspectedAt: "2026-07-20T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T002", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-21T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T002", opcuaNodeId: "ns=2;s=T002.vibration_a", inspectionType: "VIBRATION", result: "ATTENTION", findings: "Guide bearing vibration slightly above baseline; monitor.", inspectedAt: "2026-07-21T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T003", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-22T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T003", inspectionType: "LUBRICATION", result: "PASS", findings: "Oil level and quality within specification.", inspectedAt: "2026-07-22T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T004", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-23T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T004", opcuaNodeId: "ns=2;s=T004.turbine_temp", inspectionType: "THERMOGRAPHIC", result: "PASS", findings: "No hot spots detected on bearings or windings.", inspectedAt: "2026-07-23T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T005", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-24T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T005", opcuaNodeId: "ns=2;s=T005.vibration_a", inspectionType: "VIBRATION", result: "ATTENTION", findings: "Guide bearing vibration slightly above baseline; monitor.", inspectedAt: "2026-07-24T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T006", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-25T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T006", inspectionType: "LUBRICATION", result: "PASS", findings: "Oil level and quality within specification.", inspectedAt: "2026-07-25T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T007", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-26T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T007", opcuaNodeId: "ns=2;s=T007.turbine_temp", inspectionType: "THERMOGRAPHIC", result: "PASS", findings: "No hot spots detected on bearings or windings.", inspectedAt: "2026-07-26T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T008", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-27T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T008", opcuaNodeId: "ns=2;s=T008.vibration_a", inspectionType: "VIBRATION", result: "ATTENTION", findings: "Guide bearing vibration slightly above baseline; monitor.", inspectedAt: "2026-07-27T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T009", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-20T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T009", inspectionType: "LUBRICATION", result: "PASS", findings: "Oil level and quality within specification.", inspectedAt: "2026-07-20T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T010", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-21T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T010", opcuaNodeId: "ns=2;s=T010.turbine_temp", inspectionType: "THERMOGRAPHIC", result: "PASS", findings: "No hot spots detected on bearings or windings.", inspectedAt: "2026-07-21T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T011", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-22T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T011", opcuaNodeId: "ns=2;s=T011.vibration_a", inspectionType: "VIBRATION", result: "ATTENTION", findings: "Guide bearing vibration slightly above baseline; monitor.", inspectedAt: "2026-07-22T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T012", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-23T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T012", inspectionType: "LUBRICATION", result: "PASS", findings: "Oil level and quality within specification.", inspectedAt: "2026-07-23T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T013", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-24T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T013", opcuaNodeId: "ns=2;s=T013.turbine_temp", inspectionType: "THERMOGRAPHIC", result: "PASS", findings: "No hot spots detected on bearings or windings.", inspectedAt: "2026-07-24T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T014", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-25T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T014", opcuaNodeId: "ns=2;s=T014.vibration_a", inspectionType: "VIBRATION", result: "ATTENTION", findings: "Guide bearing vibration slightly above baseline; monitor.", inspectedAt: "2026-07-25T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T015", inspectionType: "VISUAL", result: "PASS", findings: "Casing, fasteners, and seals visually normal.", inspectedAt: "2026-07-26T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
  { equipmentId: "EQUIP_RTI_T015", inspectionType: "LUBRICATION", result: "PASS", findings: "Oil level and quality within specification.", inspectedAt: "2026-07-26T09:00:00", nextDueAt: "2026-10-15T09:00:00" },
]

export interface SeedSparePart {
  partNumber: string; name: string; category: string; equipmentType: string
  quantityOnHand: number; reorderLevel: number; storageLocation: string
  unitCostUsd?: number; lastRestockedAt?: string
}
export const seedSpareParts: SeedSparePart[] = [
  { partNumber: "SP-BRG-1001", name: "Guide bearing pad set", category: "BEARING", equipmentType: "TURB", quantityOnHand: 6, reorderLevel: 4, storageLocation: "Warehouse A-01", unitCostUsd: 4200.0, lastRestockedAt: "2026-06-10" },
  { partNumber: "SP-BRG-1002", name: "Thrust bearing segment", category: "BEARING", equipmentType: "TURB", quantityOnHand: 2, reorderLevel: 3, storageLocation: "Warehouse A-01", unitCostUsd: 5100.0, lastRestockedAt: "2026-05-22" },
  { partNumber: "SP-SEAL-2001", name: "Main shaft seal kit", category: "SEAL", equipmentType: "TURB", quantityOnHand: 9, reorderLevel: 5, storageLocation: "Warehouse A-02", unitCostUsd: 880.0, lastRestockedAt: "2026-06-28" },
  { partNumber: "SP-SEAL-2002", name: "Guide vane seal ring", category: "SEAL", equipmentType: "TURB", quantityOnHand: 3, reorderLevel: 4, storageLocation: "Warehouse A-02", unitCostUsd: 640.0, lastRestockedAt: "2026-04-30" },
  { partNumber: "SP-SEN-3001", name: "Vibration probe (eddy current)", category: "SENSOR", equipmentType: "TURB", quantityOnHand: 12, reorderLevel: 6, storageLocation: "Store B-11", unitCostUsd: 1350.0, lastRestockedAt: "2026-07-05" },
  { partNumber: "SP-SEN-3002", name: "RTD temperature sensor", category: "SENSOR", equipmentType: "TURB", quantityOnHand: 20, reorderLevel: 8, storageLocation: "Store B-11", unitCostUsd: 210.0, lastRestockedAt: "2026-07-12" },
  { partNumber: "SP-SEN-3003", name: "Pressure transducer", category: "SENSOR", equipmentType: "TURB", quantityOnHand: 7, reorderLevel: 6, storageLocation: "Store B-12", unitCostUsd: 490.0, lastRestockedAt: "2026-06-18" },
  { partNumber: "SP-VAL-4001", name: "Guide vane servo valve", category: "VALVE", equipmentType: "TURB", quantityOnHand: 2, reorderLevel: 2, storageLocation: "Warehouse A-03", unitCostUsd: 7300.0, lastRestockedAt: "2026-03-15" },
  { partNumber: "SP-VAL-4002", name: "Cooling water control valve", category: "VALVE", equipmentType: "TURB", quantityOnHand: 5, reorderLevel: 3, storageLocation: "Warehouse A-03", unitCostUsd: 1120.0, lastRestockedAt: "2026-06-02" },
  { partNumber: "SP-ELE-5001", name: "Excitation control card", category: "ELECTRICAL", equipmentType: "TURB", quantityOnHand: 4, reorderLevel: 3, storageLocation: "Store B-20", unitCostUsd: 2650.0, lastRestockedAt: "2026-05-09" },
  { partNumber: "SP-ELE-5002", name: "Governor PLC module", category: "ELECTRICAL", equipmentType: "TURB", quantityOnHand: 1, reorderLevel: 2, storageLocation: "Store B-20", unitCostUsd: 3900.0, lastRestockedAt: "2026-02-27" },
  { partNumber: "SP-ELE-5003", name: "Field cabling loom", category: "ELECTRICAL", equipmentType: "TURB", quantityOnHand: 14, reorderLevel: 6, storageLocation: "Store B-21", unitCostUsd: 180.0, lastRestockedAt: "2026-07-20" },
]

export interface SeedAsset3DModel {
  equipmentId: string; modelName: string; format: string; modelUrl: string
  thumbnailUrl?: string; fileSizeMb?: number; version?: string; updatedAt: string
}
export const seedAsset3DModels: SeedAsset3DModel[] = [
  { equipmentId: "EQUIP_RTI_T001", modelName: "Turbine T001 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 9.5, version: "v1.1", updatedAt: "2026-07-11T12:00:00" },
  { equipmentId: "EQUIP_RTI_T002", modelName: "Turbine T002 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 11.0, version: "v1.2", updatedAt: "2026-07-12T12:00:00" },
  { equipmentId: "EQUIP_RTI_T003", modelName: "Turbine T003 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 12.5, version: "v1.3", updatedAt: "2026-07-13T12:00:00" },
  { equipmentId: "EQUIP_RTI_T004", modelName: "Turbine T004 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 14.0, version: "v1.4", updatedAt: "2026-07-14T12:00:00" },
  { equipmentId: "EQUIP_RTI_T005", modelName: "Turbine T005 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 8.0, version: "v1.5", updatedAt: "2026-07-15T12:00:00" },
  { equipmentId: "EQUIP_RTI_T006", modelName: "Turbine T006 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 9.5, version: "v1.6", updatedAt: "2026-07-16T12:00:00" },
  { equipmentId: "EQUIP_RTI_T007", modelName: "Turbine T007 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 11.0, version: "v1.7", updatedAt: "2026-07-17T12:00:00" },
  { equipmentId: "EQUIP_RTI_T008", modelName: "Turbine T008 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 12.5, version: "v1.8", updatedAt: "2026-07-18T12:00:00" },
  { equipmentId: "EQUIP_RTI_T009", modelName: "Turbine T009 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 14.0, version: "v1.9", updatedAt: "2026-07-19T12:00:00" },
  { equipmentId: "EQUIP_RTI_T010", modelName: "Turbine T010 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 8.0, version: "v1.10", updatedAt: "2026-07-20T12:00:00" },
  { equipmentId: "EQUIP_RTI_T011", modelName: "Turbine T011 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 9.5, version: "v1.11", updatedAt: "2026-07-21T12:00:00" },
  { equipmentId: "EQUIP_RTI_T012", modelName: "Turbine T012 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 11.0, version: "v1.12", updatedAt: "2026-07-22T12:00:00" },
  { equipmentId: "EQUIP_RTI_T013", modelName: "Turbine T013 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 12.5, version: "v1.13", updatedAt: "2026-07-23T12:00:00" },
  { equipmentId: "EQUIP_RTI_T014", modelName: "Turbine T014 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 14.0, version: "v1.14", updatedAt: "2026-07-24T12:00:00" },
  { equipmentId: "EQUIP_RTI_T015", modelName: "Turbine T015 digital twin", format: "GLB", modelUrl: "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/Models/DamagedHelmet/glTF-Binary/DamagedHelmet.glb", fileSizeMb: 8.0, version: "v1.15", updatedAt: "2026-07-10T12:00:00" },
]

