import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { mapPublicEnvForFramework, parseEnvContent } from '@microsoft/rayfin-tools-common/_internal/config'

const bindingKey = 'RAYFIN_PUBLIC_ONTOLOGY_GRAPH_BINDING'
const guid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const isRecord = value => value !== null && typeof value === 'object' && !Array.isArray(value)

export function canonicalGraphBinding(raw, workspaceId) {
  let value = raw.trim()
  if (!value || value === "''" || value === '""') return ''
  const cliQuoted = value.startsWith('"') && value.endsWith('"')
  if (value.startsWith("'") && value.endsWith("'")) value = value.slice(1, -1)
  if (value.length > 1024 * 1024) throw new Error('Ontology graph binding exceeds the producer size limit.')
  let binding
  // Rayfin 1.36 writes JSON-string escaping but reads only the surrounding quotes.
  // Reverse only that bounded, known encoding at the producer, never in the app.
  for (let layer = 0; layer < 16; layer++) {
    try {
      const decoded = JSON.parse(value)
      if (isRecord(decoded)) { binding = decoded; break }
      if (layer === 0 && cliQuoted && typeof decoded === 'string') { value = decoded; continue }
      break
    } catch {
      if (!cliQuoted || !value.startsWith('{') || !value.endsWith('}')) break
      try {
        const decoded = JSON.parse(`"${value}"`)
        if (decoded.length >= value.length) break
        value = decoded
      } catch { break }
    }
  }
  if (!binding || !['workspaceId', 'ontologyId', 'graphModelId'].every(key =>
    typeof binding[key] === 'string' && guid.test(binding[key]))) {
    throw new Error('Invalid ontology graph binding: provide JSON with three verified GUIDs.')
  }
  if (binding.workspaceId.toLowerCase() !== workspaceId?.toLowerCase()) {
    throw new Error('Ontology graph binding does not match the configured workspace.')
  }
  for (const key of ['nodeTypes', 'edgeTypes']) {
    if (binding[key] !== undefined && (!isRecord(binding[key]) ||
      !Object.entries(binding[key]).every(([alias, target]) => alias.trim() && typeof target === 'string' && target.trim()))) {
      throw new Error(`Ontology graph binding ${key} must map aliases to exact ontology names.`)
    }
  }
  // Single-quoted dotenv preserves JSON escapes and #. Encode apostrophes and
  // dollars inside JSON so neither dotenv delimiters nor Vite expansion change it.
  return JSON.stringify(binding)
    .replace(/\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4})/g, escape =>
      `\\u${JSON.parse(`"${escape}"`).charCodeAt(0).toString(16).padStart(4, '0')}`)
    .replaceAll("'", '\\u0027').replaceAll('$', '\\u0024')
}

function dotenvValue(value) {
  for (const quote of ["'", '`', '"']) {
    if (!value.includes(quote) && !(quote === '"' && /\\[nr]/.test(value))) return `${quote}${value}${quote}`
  }
  throw new Error('A public environment value contains unsupported mixed quote delimiters.')
}

export function prepareFrontendEnv(source) {
  const values = parseEnvContent(source)
  const bindingLines = source.split(/\r?\n/).filter(line =>
    new RegExp(`^\\s*(?:export\\s+)?${bindingKey}\\s*=`).test(line))
  if (bindingLines.length > 1) throw new Error('Duplicate ontology graph binding in rayfin/.env.')
  let primary = source
  if (bindingLines.length) {
    const line = bindingLines[0]
    const binding = canonicalGraphBinding(line.slice(line.indexOf('=') + 1), values.get('RAYFIN_PUBLIC_WORKSPACE_ID'))
    values.set(bindingKey, binding)
    primary = source.replace(line, () => `${bindingKey}=${binding ? `'${binding}'` : ''}`)
  }
  const mapped = mapPublicEnvForFramework(values, 'vite')
  const frontend = [
    '# Generated by npm run env from rayfin/.env; do not edit.',
    ...Array.from(mapped, ([key, value]) => `${key}=${dotenvValue(value)}`),
    '',
  ].join('\n')
  return { primary, frontend }
}

export async function exportFrontendEnv(projectRoot = fileURLToPath(new URL('../', import.meta.url))) {
  const primaryPath = path.join(projectRoot, 'rayfin', '.env')
  const source = await readFile(primaryPath, 'utf8')
  const { primary, frontend } = prepareFrontendEnv(source)
  if (primary !== source) await writeFile(primaryPath, primary, 'utf8')
  await writeFile(path.join(projectRoot, '.env.local'), frontend, 'utf8')
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  try {
    await exportFrontendEnv()
    console.log('Exported Vite public configuration; ontology binding JSON validated when configured.')
  } catch (error) {
    console.error(error.message)
    process.exitCode = 1
  }
}
